src/Entity/Forecast.php
<?php

namespace App\Entity;

use App\Repository\ForecastRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\Ignore;

#[ORM\Entity(repositoryClass: ForecastRepository::class)]
class Forecast
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Groups(['api'])]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column]
    #[Groups(['api'])]
    private ?int $temperatureCelsius = null;

    #[ORM\Column]
    #[Groups(['api'])]
    private ?int $flTemperatureCelsius = null;

    #[ORM\Column(nullable: true)]
    #[Groups(['api'])]
    private ?int $pressure = null;

    #[ORM\Column(nullable: true)]
    #[Groups(['api'])]
    private ?int $humidity = null;

    #[ORM\Column(nullable: true)]
    #[Groups(['api'])]
    private ?float $windSpeed = null;

    #[ORM\Column(nullable: true)]
    #[Groups(['api'])]
    private ?int $windDeg = null;

    #[ORM\Column(nullable: true)]
    #[Groups(['api'])]
    private ?int $cloudiness = null;

    #[ORM\Column(length: 255)]
    #[Groups(['api'])]
    private ?string $icon = null;

    #[ORM\ManyToOne(inversedBy: 'forecasts')]
    #[ORM\JoinColumn(nullable: false)]
    // #[Ignore]
    private ?Location $location = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getTemperatureCelsius(): ?int
    {
        return $this->temperatureCelsius;
    }

    public function setTemperatureCelsius(int $temperatureCelsius): static
    {
        $this->temperatureCelsius = $temperatureCelsius;

        return $this;
    }

    public function getTemperatureFahrenheit(): ?int
    {
        return round(($this->getTemperatureCelsius() * 9 / 5) + 32);
    }

    public function getFlTemperatureCelsius(): ?int
    {
        return $this->flTemperatureCelsius;
    }

    public function setFlTemperatureCelsius(int $flTemperatureCelsius): static
    {
        $this->flTemperatureCelsius = $flTemperatureCelsius;

        return $this;
    }

    public function getFlTemperatureFahrenheit(): ?int
    {
        return round(($this->getFlTemperatureCelsius() * 9 / 5) + 32);
    }

    public function getPressure(): ?int
    {
        return $this->pressure;
    }

    public function setPressure(?int $pressure): static
    {
        $this->pressure = $pressure;

        return $this;
    }

    public function getHumidity(): ?int
    {
        return $this->humidity;
    }

    public function setHumidity(?int $humidity): static
    {
        $this->humidity = $humidity;

        return $this;
    }

    public function getWindSpeed(): ?float
    {
        return $this->windSpeed;
    }

    public function setWindSpeed(?float $windSpeed): static
    {
        $this->windSpeed = $windSpeed;

        return $this;
    }

    public function getWindDeg(): ?int
    {
        return $this->windDeg;
    }

    public function setWindDeg(?int $windDeg): static
    {
        $this->windDeg = $windDeg;

        return $this;
    }

    public function getCloudiness(): ?int
    {
        return $this->cloudiness;
    }

    public function setCloudiness(?int $cloudiness): static
    {
        $this->cloudiness = $cloudiness;

        return $this;
    }

    public function getIcon(): ?string
    {
        return $this->icon;
    }

    public function setIcon(string $icon): static
    {
        $this->icon = $icon;

        return $this;
    }

    public function getLocation(): ?Location
    {
        return $this->location;
    }

    public function setLocation(?Location $location): static
    {
        $this->location = $location;

        return $this;
    }
}

src/Controller/WeatherController.php
<?php

namespace App\Controller;

use App\Exception\LocationNotFoundException;
use App\Service\ForecastService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class WeatherController extends AbstractController
{
    #[Route('/weather/{countryCode}/{city}', name: 'app_weather')]
    public function forecast(
        ForecastService $forecastService,
        string $countryCode, 
        string $city
        ): Response
    {
        try {
            list($location, $forecasts) = $forecastService->getForecastsForLocationName($countryCode, $city);
        } catch (LocationNotFoundException $e) {
            throw $this->createNotFoundException('Location not found');
        }

        return $this->render('weather/forecast.html.twig', [
            'forecasts' => $forecasts,
            'location' => $location
        ]);
    }
}

templates/weather/forecast.html.twig
{% extends 'layout_boxed.html.twig' %}

{% block title %}{{ location.name }}, {{ location.countryCode }} Weather Forecast{% endblock %}

{% block content %}
    <div class="row mt-3">
        <div class="col">
            <h1>Forecast for {{ location.name  }}, {{ location.countryCode }}</h1>
        </div>
    </div>
    

    <div class="row">
        <div class="col">
            <div id="map" class="forecast-card mt-3" style="height: 180px;"></div>
        </div>
    </div>

    <div class="row forecasts mt-3">
    {% for forecast in forecasts %}

        <div class="col-12 col-lg-6">
            <div class="forecast-card">
                <div class="row">
                    <div class="forecast-card-header col-xs-12 d-flex justify-content-between align-middle">
                        <div class="day">{{ forecast.date|date('l') }}</div>
                        <div class="date">{{ forecast.date|date('d.m') }}</div>
                    </div>
                    <div class="forecast-card-general col-12 col-lg-6">
                        <div class="row">
                            <div class="col-6 text-center">
                                <i class="bi-{{ forecast.icon }} forecast-icon"></i>
                            </div>
                            <div class="col-6">
                                <div class="temperature">{{ forecast.temperatureCelsius }}&deg;</div>
                                <div class="fl-temperature">Feels like {{ forecast.flTemperatureCelsius }}&deg;</div>
                            </div>
                        </div>
                    </div>
                    <div class="forecast-card-details col-12 col-lg-6 mt-3">
                        <dl>
                            <dt>Pressure</dt>
                            <dd>{{ forecast.pressure }}</dd>

                            <dt>Humidity</dt>
                            <dd>{{ forecast.humidity }}%</dd>

                            <dt>Wind</dt>
                            <dd>{{ forecast.windSpeed }} m/s</dd>

                            <dt>Cloudiness</dt>
                            <dd>{{ forecast.cloudiness }}%</dd>

                            <dt>Fahrenheit</dt>
                            <dd>{{ forecast.temperatureFahrenheit }}&deg;F</dd>

                            <dt>Feels like</dt>
                            <dd>{{ forecast.flTemperatureFahrenheit }}&deg;F</dd>
                        </dl>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>

    
    
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
    <script>
        var map = L.map('map').setView([{{ location.latitude }}, {{ location.longitude }}], 10);

        L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
            maxZoom: 19,
            attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
        }).addTo(map);

        var marker = L.marker([{{ location.latitude }}, {{ location.longitude }}]).addTo(map);
    </script>
{% endblock %}